//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookids
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookidsContainer : DbContext
    {
        public BookidsContainer()
            : base("name=BookidsContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pessoas> PessoasSet { get; set; }
        public virtual DbSet<Inscricoes> InscricoesSet { get; set; }
        public virtual DbSet<Compras> ComprasSet { get; set; }
        public virtual DbSet<DetalhesCompra> DetalhesCompraSet { get; set; }
        public virtual DbSet<Produtos> ProdutosSet { get; set; }
        public virtual DbSet<TipoProduto> TipoProdutoSet { get; set; }
        public virtual DbSet<Escolas> EscolasSet { get; set; }
        public virtual DbSet<Colaboracoes> ColaboracoesSet { get; set; }
        public virtual DbSet<Participacoes> ParticipacoesSet { get; set; }
        public virtual DbSet<Eventos> EventosSet { get; set; }
        public virtual DbSet<Users> UsersSet { get; set; }
    }
}
